CREATE TABLE `cart_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`productId` varchar(64) NOT NULL,
	`productName` varchar(255) NOT NULL,
	`productData` json NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`unitPrice` decimal(10,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cart_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`vizlyncOrderId` varchar(64),
	`stripePaymentIntentId` varchar(255),
	`stripeSessionId` varchar(255),
	`productId` varchar(64) NOT NULL,
	`productName` varchar(255) NOT NULL,
	`productData` json NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`unitPrice` decimal(10,2) NOT NULL,
	`totalAmount` decimal(10,2) NOT NULL,
	`currency` varchar(8) NOT NULL DEFAULT 'USD',
	`status` enum('pending_payment','paid','processing','completed','failed','refunded') NOT NULL DEFAULT 'pending_payment',
	`esimData` json,
	`startDate` varchar(16),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `products_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`planInfo` text,
	`price` decimal(10,2) NOT NULL,
	`validityDays` int,
	`countries` json,
	`region` json,
	`dataAmount` decimal(10,3),
	`dataUnit` varchar(16),
	`speed` varchar(32),
	`planType` varchar(32),
	`category` varchar(32),
	`networkName` varchar(128),
	`networkType` varchar(64),
	`isVoiceAvailable` boolean DEFAULT false,
	`isSmsAvailable` boolean DEFAULT false,
	`hotspotAvailable` boolean DEFAULT false,
	`topUpAvailable` boolean DEFAULT false,
	`profile` varchar(32),
	`activationPolicy` varchar(128),
	`startDateEnabled` boolean DEFAULT false,
	`voiceMin` int,
	`sms` int,
	`rawData` json,
	`syncedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_cache_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_cache_productId_unique` UNIQUE(`productId`)
);
