CREATE TABLE `articles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`coverImage` text,
	`article_status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`authorId` int,
	`titleZhTW` varchar(512),
	`excerptZhTW` text,
	`contentZhTW` text,
	`titleZhCN` varchar(512),
	`excerptZhCN` text,
	`contentZhCN` text,
	`titleEn` varchar(512),
	`excerptEn` text,
	`contentEn` text,
	`titleJa` varchar(512),
	`excerptJa` text,
	`contentJa` text,
	`titleKo` varchar(512),
	`excerptKo` text,
	`contentKo` text,
	`titleTh` varchar(512),
	`excerptTh` text,
	`contentTh` text,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `articles_slug_unique` UNIQUE(`slug`)
);
